#! /bin/bash

_go()
{
    COMPREPLY=()
    
    if test -f "/tmp/go.list" 
    then
        local -A gomap;
        while read line; do
            kv_arr=($line)
            # echo $line
            # echo ${kv_arr[0]}
            # echo $1
            gomap[${kv_arr[0]}]=${kv_arr[1]}
            if [[ ${kv_arr[0]} == $2* ]];
            then
                # echo ${kv_arr[1]}
                COMPREPLY[${#COMPREPLY[*]}]=${kv_arr[0]}
            fi
        done < /tmp/go.list
    fi

    return 0
}

# _go $1
complete -F _go go.sh
complete -F _go go
complete -F _go codedir