server:
  port: 8080


my:
  datasource:
    ds1:
      url: jdbc:mysql://192.168.2.159:3306/db_test?socketTimeout=15000
      user: root
      password: root
    ds2:
      url: jdbc:mysql://192.168.2.170:63306/db_test?socketTimeout=15000
      user: root
      password: 123456
